name: Playwright Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: http://www.uitestingplayground.com
      STAGING_BASE_URL: https://automationexercise.com
      API_BASE: https://reqres.in/api
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --force
          npm install -D allure-playwright allure-commandline --force

      - name: Install Playwright browsers
        run: npx playwright install --with-deps --force

      - name: Run Playwright tests with Allure
        run: npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure Report
        if: always()
        run: npx allure generate allure-results --clean -o allure-report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/